version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
                CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        environment:
            - CLIENT_PORT=${CLIENT_PORT}
            - SERVER_PORT=${SERVER_PORT}
        networks: 
            - awesome

    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
                SERVER_PORT: ${SERVER_PORT}
        depends_on:
            - client
            - postgres
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            CLIENT_URL: prakticum-client:80
            SERVER_PORT: ${SERVER_PORT}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        networks: 
            - awesome

    postgres:
        container_name: prakticum-postgres
        image: postgres:14
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        networks: 
            - awesome
        restart: always
        expose: 
            - "${POSTGRES_PORT}"

networks:
    awesome:
        driver: bridge
