export enum Paths {
    main = '/',
    login = '/login',
    register = '/register',
    profile = '/profile',
    editProfile = '/edit-profile',
    editPassword = '/edit-password',
    feed = '/feed',
    startScreen = '/start-screen',
    endScreenSuccess = '/end-screen-success',
    endScreenFail = '/end-screen-fail',
    leaderBoard = '/leader-board',
    game = '/game',
    notFound = '*',
    error = '/error',
}
